# Reading file using Pandas

In [1]:
from google.colab import files
uploaded = files.upload()
type(uploaded)

Saving gapminder.tsv to gapminder.tsv

dict

In Python, the io module stands for "Input/Output" and provides classes for handling input and output operations. The io module allows you to work with streams of data, such as files, strings, and network connections, in a unified way.

When you see the line import io, it means that the code is importing the io module so that its classes and functions can be used in the current script or program.

In the context of the code you provided earlier, where you're using Google Colab to upload files, the io module is often used in conjunction with the files.upload() function to handle the uploaded files as streams of data. After using files.upload(), the uploaded files are stored as dictionary-like objects containing bytes-like objects. The io.BytesIO class from the io module can be used to work with these bytes-like objects as file-like objects.bold text

In [3]:
import io
myfile=io.BytesIO(uploaded['gapminder.tsv'])

myfile = io.BytesIO(uploaded['gapminder.tsv']): This line creates a io.BytesIO object named myfile and initializes it with the content of the 'gapminder.tsv' file that was uploaded using Google Colab's files.upload() function.

uploaded['gapminder.tsv'] retrieves the uploaded file named 'gapminder.tsv' from the dictionary-like object returned by files.upload().
io.BytesIO() is used to create astream-like object that allows you to work with the bytes from the file inmemory.

In [4]:
import pandas
df = pandas.read_csv(myfile , sep='\t')

EmptyDataError: ignored

In [5]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.shape

(1704, 6)

In [8]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [12]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [13]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [14]:
df.info

<bound method DataFrame.info of           country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]>

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [18]:
df.sample(5)

                  country continent  year  lifeExp       pop     gdpPercap
1499                Syria      Asia  2007   74.143  19314747   4184.548089
899               Liberia    Africa  2007   45.678   3193942    414.507341
940              Malaysia      Asia  1972   63.010  11441462   2849.094780
1701             Zimbabwe    Africa  1997   46.809  11404948    792.449960
1558  Trinidad and Tobago  Americas  2002   68.976   1101832  11460.600230

In [20]:
df.tail(5)

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [22]:
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [32]:
year=df['year']

In [25]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [26]:
type(df)

pandas.core.frame.DataFrame

In [33]:
type(year)

pandas.core.series.Series

In [34]:
year

0       1952
1       1957
2       1962
3       1967
4       1972
        ...
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: year, Length: 1704, dtype: int64

In [35]:
year.sum()

3373068

In [30]:
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [36]:
year.mean()

1979.5

In [37]:
year.max()

2007

In [38]:
year.median()

1979.5

In [40]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [41]:
df.tail()

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [42]:
df.info

<bound method DataFrame.info of           country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]>

In [43]:
df.iloc[420:430,]

      country continent  year  lifeExp     pop    gdpPercap
420  Djibouti    Africa  1952   34.812   63149  2669.529475
421  Djibouti    Africa  1957   37.328   71851  2864.969076
422  Djibouti    Africa  1962   39.693   89898  3020.989263
423  Djibouti    Africa  1967   42.074  127617  3020.050513
424  Djibouti    Africa  1972   44.366  178848  3694.212352
425  Djibouti    Africa  1977   46.519  228694  3081.761022
426  Djibouti    Africa  1982   48.812  305991  2879.468067
427  Djibouti    Africa  1987   50.040  311025  2880.102568
428  Djibouti    Africa  1992   51.604  384156  2377.156192
429  Djibouti    Africa  1997   53.157  417908  1895.016984

In [45]:
type(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

NoneType

In [46]:
df.info

<bound method DataFrame.info of           country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]>

In [59]:
df.iloc[0:1704,0:3]

          country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

In [50]:
df_country=df['country']

In [51]:
df_country.info

<bound method Series.info of 0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object>

In [52]:
df.info

<bound method DataFrame.info of           country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]>

In [60]:
# Take a subset with only Country, Year and life expectancy
df_subset=df.iloc[:,[0,2,3]]

In [61]:
df_subset.info

<bound method DataFrame.info of           country  year  lifeExp
0     Afghanistan  1952   28.801
1     Afghanistan  1957   30.332
2     Afghanistan  1962   31.997
3     Afghanistan  1967   34.020
4     Afghanistan  1972   36.088
...           ...   ...      ...
1699     Zimbabwe  1987   62.351
1700     Zimbabwe  1992   60.377
1701     Zimbabwe  1997   46.809
1702     Zimbabwe  2002   39.989
1703     Zimbabwe  2007   43.487

[1704 rows x 3 columns]>

In [62]:
df_subset.columns

Index(['country', 'year', 'lifeExp'], dtype='object')

In [63]:
df_subset['year'].mean()

1979.5

In [64]:
df['year'].mean()

1979.5

In [65]:
## groupby

In [69]:
df.groupby('country')

In [71]:
df['country'].count()

1704

In [72]:
df_subset.groupby('country')

In [74]:
df_subset.groupby('country').median()

                      year  lifeExp
country
Afghanistan         1979.5  39.1460
Albania             1979.5  69.6750
Algeria             1979.5  59.6910
Angola              1979.5  39.6945
Argentina           1979.5  69.2115
...                    ...      ...
Vietnam             1979.5  57.2900
West Bank and Gaza  1979.5  62.5855
Yemen, Rep.         1979.5  46.6440
Zambia              1979.5  46.0615
Zimbabwe            1979.5  53.1765

[142 rows x 2 columns]

In [77]:
df_subset.groupby('year').mean()

<ipython-input-77-e702c7476a51>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_subset.groupby('year').mean()

        lifeExp
year
1952  49.057620
1957  51.507401
1962  53.609249
1967  55.678290
1972  57.647386
1977  59.570157
1982  61.533197
1987  63.212613
1992  64.160338
1997  65.014676
2002  65.694923
2007  67.007423

In [78]:
## grouping by both country and year

In [81]:
df_subset.groupby(['year','country']).mean()

                         lifeExp
year country
1952 Afghanistan          28.801
     Albania              55.230
     Algeria              43.077
     Angola               30.015
     Argentina            62.485
...                          ...
2007 Vietnam              74.249
     West Bank and Gaza   73.422
     Yemen, Rep.          62.698
     Zambia               42.384
     Zimbabwe             43.487

[1704 rows x 1 columns]

In [92]:
df.groupby(['continent','country','year'])['lifeExp'].count()

continent  country      year
Africa     Algeria      1952    1
                        1957    1
                        1962    1
                        1967    1
                        1972    1
                               ..
Oceania    New Zealand  1987    1
                        1992    1
                        1997    1
                        2002    1
                        2007    1
Name: lifeExp, Length: 1704, dtype: int64

In [93]:
## Now we would like to group the given data by continent,country anddd finf the mean of lifeExp, pop

In [101]:
df.groupby(['continent','country'])['pop','lifeExp'].sum()

<ipython-input-101-a9073eab2221>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['continent','country'])['pop','lifeExp'].sum()

                                pop  lifeExp
continent country
Africa    Algeria         238504874  708.362
          Angola           87712681  454.602
          Benin            48209960  585.359
          Botswana         11654234  655.170
          Burkina Faso     90584127  536.328
...                             ...      ...
Europe    Switzerland      76611518  906.781
          Turkey          550908099  716.357
          United Kingdom  673053608  887.071
Oceania   Australia       175791750  895.955
          New Zealand      37200386  887.874

[142 rows x 2 columns]

In [102]:
# again adding another attribute to the grouping thai is year
#how ever the mean or sum wont convey any meang to it

In [104]:
df.groupby(['continent','country','year'])['pop','lifeExp'].sum()

<ipython-input-104-8373b4fac174>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['continent','country','year'])['pop','lifeExp'].sum()

                                 pop  lifeExp
continent country     year
Africa    Algeria     1952   9279525   43.077
                      1957  10270856   45.685
                      1962  11000948   48.303
                      1967  12760499   51.407
                      1972  14760787   54.518
...                              ...      ...
Oceania   New Zealand 1987   3317166   74.320
                      1992   3437674   76.330
                      1997   3676187   77.550
                      2002   3908037   79.110
                      2007   4115771   80.204

[1704 rows x 2 columns]

In [107]:
df.groupby(['continent','country','year'])['pop','lifeExp'].sum()

<ipython-input-107-8373b4fac174>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['continent','country','year'])['pop','lifeExp'].sum()

                                 pop  lifeExp
continent country     year
Africa    Algeria     1952   9279525   43.077
                      1957  10270856   45.685
                      1962  11000948   48.303
                      1967  12760499   51.407
                      1972  14760787   54.518
...                              ...      ...
Oceania   New Zealand 1987   3317166   74.320
                      1992   3437674   76.330
                      1997   3676187   77.550
                      2002   3908037   79.110
                      2007   4115771   80.204

[1704 rows x 2 columns]

In [109]:
df.groupby(['continent','country','year'])['pop','lifeExp'].median()

<ipython-input-109-63179028e451>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['continent','country','year'])['pop','lifeExp'].median()

                                   pop  lifeExp
continent country     year
Africa    Algeria     1952   9279525.0   43.077
                      1957  10270856.0   45.685
                      1962  11000948.0   48.303
                      1967  12760499.0   51.407
                      1972  14760787.0   54.518
...                                ...      ...
Oceania   New Zealand 1987   3317166.0   74.320
                      1992   3437674.0   76.330
                      1997   3676187.0   77.550
                      2002   3908037.0   79.110
                      2007   4115771.0   80.204

[1704 rows x 2 columns]

In [116]:
df.iloc[:10,:]

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351